import { auth } from "@/auth";
import { Modals } from "@/components/modals";
import { Porviders } from "@/components/providers";
import { SubscriptionAlert } from "@/features/subscriptions/components/subscription-alert";
import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Porviders>
            <Analytics />
            <Toaster />
            <Modals />
            <SubscriptionAlert />
            {children}
          </Porviders>
        </body>
      </SessionProvider>
    </html>
  );
}
